### ISSUE TITLE
Perl support for MathJax?

### ISSUE THREAD

**Issue by PhilterPaper** [jberger/Acme-Pod-MathJax#1]
From reading the description for this package, I'm not sure this is anywhere near what I need, but I'll ask anyway. I need a Perl package that will take MathJax markup and turn it into either (X)HTML or some sort of data structure that I can figure out how to draw. I own the PDF-production package PDF::Builder, and would like to add equation handling to it. I don't think I can invoke a browser and Javascript on-the-fly (any suggestions? Selenium doesn't appear to be well-enough supported in Perl), and was hoping to find some Perl package that had a Javascript  engine that could run MathJax and transform the markup into HTML (which I could capture and process to PDF). Does anyone know of such a thing? I've heard of JE and JavaScript::V8, but my understanding is that they are APIs to external JS engines (neither Perl extensions or pure Perl).

A general-purpose Javascript engine that could run all sorts of JS scripts and output the resulting DOM in HTML would really find a lot of application in the Perl world. Does such a thing exist?

By the way, I haven't seen this POD rendered correctly anywhere. The HTML appears to be missing these lines:
```
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.1/es5/tex-mml-chtml.js"></script>
```
Manually added to the captured HTML file, it renders the examples beautifully. Unfortunately, I'm not aware of any way to add content to the `<head>` of the POD renderer, nor to add arbitrary content to the `<body>` (either would likely be viewed as a security risk).

**Comment by jberger** [comment]
You are correct that this is not at all the module you need. As indicated by the fact that it is in the ACME namespace, this isn't really a useful module at all. This is essentially a test module so that I could test if MathJax would render in different pod renderers. Imagine if say metacpan could render via mathjax you'd need a module to see to test it. Honestly it has been so long since then I don't recall if/where support was added. metacpan does not appear to support it https://metacpan.org/pod/Acme::Pod::MathJax.

You're right that all that's needed are those extra libraries, however they are rather heavy and since they are rarely used most renderers don't want to pay the loading tax if they aren't needed. And you are also correct that most user-submitted content cannot inject javascript for fear of XSS attacks.

To your other point, yes to backend render html from mathjax you'd need to shell out to a JS engine, much easier just to front-end render. There have been modules to handle such interaction in the backend, but I'm not sure any are worth considering.

**Comment by PhilterPaper** [comment]
An afterthought: you have recommended HTML code for adding the "Powered by MathJax" button. Please consider changing `border="0"` in it to `style="border: 0;"` so that the W3C Validator will stop complaining about it (the `border` attribute is deprecated). Thanks!

**Comment by jberger** [comment]
> you have recommended HTML code for adding the "Powered by MathJax" button

What? To the best of my recollection this module has no html in it. This is a pod document.

**Comment by PhilterPaper** [comment]
https://docs.mathjax.org/en/latest/misc/badges.html is what I'm referring to. I was thinking "you" were associated with MathJax. Apparently not. NVM, I will post the request elsewhere.
